name: terraform-lint
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]  

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Check the code security
      uses: actions/checkout@main
    - name: Lint-Terraform
      uses: actionshub/terraform-lint@main
